name: e2e
on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  TOKEN: ${{secret.GITHUB_TOKEN}}

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
        name: Checkout source code
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.40.1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Turn on longpaths for git
        run: git config core.longpaths true
      - name: Run install
        run: make install
      - name: Run e2e tests
        run: make e2e